-- catalogoItens.lua
-- Extraido da secao "Equipamentos" do .bib: 68 itens, cada um em duas
-- qualidades (Comum e Otima).
--
-- Campos possiveis por item:
--   durabilidade   pontos de uso antes de quebrar
--   dado           dado de dano ou de efeitos
--   alcance        em metros
--   reqAtributo/reqValor   minimo exigido para equipar
--   absorcao       % de dano absorvido (armaduras)
--   deslocamento   penalidade de movimento, em metros (negativo)
--   defesaEscolha  bonus em DUAS defesas a escolha do jogador
--   defesaAparar   bonus fixo em Defesa - Aparar (escudos)
--   periciaBonus/periciaNome   bonus numa pericia especifica
--   danoExtra / alcanceExtra / municoes   projeteis
--
-- MOEDAS: 1 Aureu = 50 Lunaris | 1 Lunar = 20 Florins | 1 Florin = 10 Drams

local CatalogoItens = {}

CatalogoItens.moedas = { "aureus", "lunaris", "florins", "drams" }
CatalogoItens.nomeMoeda = { aureus = "Aureus", lunaris = "Lunaris", florins = "Florins", drams = "Drams" }
-- valor de cada moeda em Drams, para comparar precos
CatalogoItens.valorEmDrams = { drams = 1, florins = 10, lunaris = 200, aureus = 10000 }

CatalogoItens.itens = {
  {
    nome = "Armadura leve",
    categoria = "Armadura",
    qualidade = "Comum",
    slot = "armadura",
    preco = { lunaris = 22 },
    durabilidade = 4,
    absorcao = 15,
    defesaEscolha = 3,
  },
  {
    nome = "Armadura leve",
    categoria = "Armadura",
    qualidade = "Ótima",
    slot = "armadura",
    preco = { lunaris = 35 },
    durabilidade = 5,
    absorcao = 25,
    defesaEscolha = 5,
  },
  {
    nome = "Armadura protetora",
    categoria = "Armadura",
    qualidade = "Comum",
    slot = "armadura",
    preco = { lunaris = 29 },
    durabilidade = 5,
    reqValor = 2,
    absorcao = 20,
    deslocamento = -5,
    defesaEscolha = 4,
    reqAtributo = "Força",
  },
  {
    nome = "Armadura protetora",
    categoria = "Armadura",
    qualidade = "Ótima",
    slot = "armadura",
    preco = { lunaris = 46 },
    durabilidade = 6,
    reqValor = 2,
    absorcao = 30,
    deslocamento = -5,
    defesaEscolha = 6,
    reqAtributo = "Força",
  },
  {
    nome = "Armadura pesada",
    categoria = "Armadura",
    qualidade = "Comum",
    slot = "armadura",
    preco = { lunaris = 48 },
    durabilidade = 6,
    reqValor = 4,
    absorcao = 25,
    deslocamento = -10,
    defesaEscolha = 5,
    reqAtributo = "Força",
  },
  {
    nome = "Armadura pesada",
    categoria = "Armadura",
    qualidade = "Ótima",
    slot = "armadura",
    preco = { aureus = 1, lunaris = 18 },
    durabilidade = 7,
    reqValor = 4,
    absorcao = 35,
    deslocamento = -10,
    defesaEscolha = 8,
    reqAtributo = "Força",
  },
  {
    nome = "Arma corpo-a-corpo de uma-mão",
    categoria = "Armas",
    qualidade = "Comum",
    slot = "maos",
    preco = { lunaris = 30 },
    durabilidade = 4,
    dado = "2d6",
  },
  {
    nome = "Arma corpo-a-corpo de uma-mão",
    categoria = "Armas",
    qualidade = "Ótima",
    slot = "maos",
    preco = { lunaris = 40 },
    durabilidade = 5,
    dado = "4d6",
  },
  {
    nome = "Arma corpo-a-corpo versátil",
    categoria = "Armas",
    qualidade = "Comum",
    slot = "maos",
    preco = { lunaris = 40 },
    durabilidade = 5,
    reqValor = 2,
    dado = "3d6",
    reqAtributo = "Força",
  },
  {
    nome = "Arma corpo-a-corpo versátil",
    categoria = "Armas",
    qualidade = "Ótima",
    slot = "maos",
    preco = { aureus = 1 },
    durabilidade = 6,
    reqValor = 2,
    dado = "5d6",
    reqAtributo = "Força",
  },
  {
    nome = "Arma corpo-a-corpo de duas-mãos",
    categoria = "Armas",
    qualidade = "Comum",
    slot = "maos",
    preco = { aureus = 1 },
    durabilidade = 5,
    reqValor = 4,
    dado = "4d6",
    reqAtributo = "Força",
  },
  {
    nome = "Arma corpo-a-corpo de duas-mãos",
    categoria = "Armas",
    qualidade = "Ótima",
    slot = "maos",
    preco = { aureus = 1, lunaris = 17 },
    durabilidade = 6,
    reqValor = 4,
    dado = "6d6",
    reqAtributo = "Força",
  },
  {
    nome = "Arco/Besta",
    categoria = "Armas",
    qualidade = "Comum",
    slot = "maos",
    preco = { lunaris = 30 },
    durabilidade = 3,
    alcance = 12,
    dado = "3d6",
  },
  {
    nome = "Arco/Besta",
    categoria = "Armas",
    qualidade = "Ótima",
    slot = "maos",
    preco = { lunaris = 40 },
    durabilidade = 4,
    alcance = 12,
    dado = "5d6",
  },
  {
    nome = "Canalizador energético",
    categoria = "Armas",
    qualidade = "Comum",
    slot = "maos",
    preco = { aureus = 1, lunaris = 20 },
    durabilidade = 4,
    alcance = 14,
    reqValor = 4,
    dado = "3d6",
    reqAtributo = "Inteligência",
  },
  {
    nome = "Canalizador energético",
    categoria = "Armas",
    qualidade = "Ótima",
    slot = "maos",
    preco = { aureus = 2 },
    durabilidade = 5,
    alcance = 14,
    reqValor = 4,
    dado = "5d6",
    reqAtributo = "Inteligência",
  },
  {
    nome = "Escudo leve",
    categoria = "Armas",
    qualidade = "Comum",
    slot = "maos",
    preco = { lunaris = 29 },
    durabilidade = 6,
    reqValor = 2,
    defesaAparar = 3,
    reqAtributo = "Força",
  },
  {
    nome = "Escudo leve",
    categoria = "Armas",
    qualidade = "Ótima",
    slot = "maos",
    preco = { lunaris = 44 },
    durabilidade = 7,
    reqValor = 2,
    defesaAparar = 5,
    reqAtributo = "Força",
  },
  {
    nome = "Escudo pesado",
    categoria = "Armas",
    qualidade = "Comum",
    slot = "maos",
    preco = { lunaris = 38 },
    durabilidade = 7,
    reqValor = 4,
    defesaAparar = 4,
    reqAtributo = "Força",
  },
  {
    nome = "Escudo pesado",
    categoria = "Armas",
    qualidade = "Ótima",
    slot = "maos",
    preco = { aureus = 1, lunaris = 10 },
    durabilidade = 8,
    reqValor = 4,
    defesaAparar = 6,
    reqAtributo = "Força",
  },
  {
    nome = "Manopla comum",
    categoria = "Armas",
    qualidade = "Comum",
    slot = "maos",
    preco = { lunaris = 36 },
    durabilidade = 3,
    reqValor = 2,
    dado = "2d4",
    reqAtributo = "Força",
  },
  {
    nome = "Manopla comum",
    categoria = "Armas",
    qualidade = "Ótima",
    slot = "maos",
    preco = { lunaris = 48 },
    durabilidade = 4,
    reqValor = 2,
    dado = "4d4",
    reqAtributo = "Força",
  },
  {
    nome = "Flechas",
    categoria = "Projéteis",
    qualidade = "Comum",
    slot = "mochila",
    preco = { florins = 2 },
    danoExtra = 1,
    municoes = 10,
  },
  {
    nome = "Flechas",
    categoria = "Projéteis",
    qualidade = "Ótima",
    slot = "mochila",
    preco = { florins = 4 },
    danoExtra = 2,
    municoes = 10,
  },
  {
    nome = "Virotes",
    categoria = "Projéteis",
    qualidade = "Comum",
    slot = "mochila",
    preco = { florins = 2 },
    alcanceExtra = 2,
    municoes = 10,
  },
  {
    nome = "Virotes",
    categoria = "Projéteis",
    qualidade = "Ótima",
    slot = "mochila",
    preco = { florins = 4 },
    alcanceExtra = 4,
    municoes = 10,
  },
  {
    nome = "Bala",
    categoria = "Projéteis",
    qualidade = "Comum",
    slot = "mochila",
    preco = { florins = 10 },
    danoExtra = 2,
    municoes = 1,
  },
  {
    nome = "Bala",
    categoria = "Projéteis",
    qualidade = "Ótima",
    slot = "mochila",
    preco = { florins = 15 },
    danoExtra = 4,
    municoes = 1,
  },
  {
    nome = "Aljava do Arqueiro",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    capacidade = 20,
    capacidadeTipo = "flechas",
  },
  {
    nome = "Aljava do Arqueiro",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    capacidade = 25,
    capacidadeTipo = "flechas",
  },
  {
    nome = "Bisturi do Curandeiro",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    periciaBonus = 2,
    periciaNome = "Medicina",
  },
  {
    nome = "Bisturi do Curandeiro",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    periciaBonus = 4,
    periciaNome = "Medicina",
  },
  {
    nome = "Botas de Corrida",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    deslocamento = 2,
  },
  {
    nome = "Botas de Corrida",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    deslocamento = 4,
  },
  {
    nome = "Caneca do Boêmio",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    periciaBonus = 2,
    periciaNome = "Boêmio",
  },
  {
    nome = "Caneca do Boêmio",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    periciaBonus = 4,
    periciaNome = "Boêmio",
  },
  {
    nome = "Caneta do Acadêmico",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    periciaBonus = 2,
    periciaOpcoes = "Acadêmicos, Ocultismo",
  },
  {
    nome = "Caneta do Acadêmico",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    periciaBonus = 4,
    periciaOpcoes = "Acadêmicos, Ocultismo",
  },
  {
    nome = "Capa do Viajante",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    periciaBonus = 2,
    periciaNome = "Furtividade",
  },
  {
    nome = "Capa do Viajante",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    periciaBonus = 4,
    periciaNome = "Furtividade",
  },
  {
    nome = "Cinto do Atirador",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    capacidade = 12,
    capacidadeTipo = "balas",
  },
  {
    nome = "Cinto do Atirador",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    capacidade = 14,
    capacidadeTipo = "balas",
  },
  {
    nome = "Cinto do Besteiro",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    capacidade = 15,
    capacidadeTipo = "virotes",
  },
  {
    nome = "Cinto do Besteiro",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    capacidade = 18,
    capacidadeTipo = "virotes",
  },
  {
    nome = "Cinto do Gladiador",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    defesaEscolha = 2,
    defesaLista = "Defesa Física - Aparar e Defesa Física - Esquiva",
  },
  {
    nome = "Cinto do Gladiador",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    defesaEscolha = 4,
    defesaLista = "Defesa Física - Aparar e Defesa Física - Esquiva",
  },
  {
    nome = "Colar do Resiliente",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    defesaEscolha = 2,
    defesaLista = "Defesa Telepática e Defesa Empática",
  },
  {
    nome = "Colar do Resiliente",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    defesaEscolha = 4,
    defesaLista = "Defesa Telepática e Defesa Empática",
  },
  {
    nome = "Instrumento do Bardo",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    periciaBonus = 2,
    periciaNome = "Performance",
  },
  {
    nome = "Instrumento do Bardo",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    periciaBonus = 4,
    periciaNome = "Performance",
  },
  {
    nome = "Jóia do Socialite",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    periciaDistribuir = 2,
    periciaOpcoes = "Negociar, Etiqueta, Diplomacia",
  },
  {
    nome = "Jóia do Socialite",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    periciaDistribuir = 4,
    periciaOpcoes = "Negociar, Etiqueta, Diplomacia",
  },
  {
    nome = "Luvas do Ladrão",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    periciaBonus = 2,
    periciaNome = "Prestidigitação",
  },
  {
    nome = "Luvas do Ladrão",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    periciaBonus = 4,
    periciaNome = "Prestidigitação",
  },
  {
    nome = "Luvas do Operário",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    periciaDistribuir = 2,
    periciaOpcoes = "Ofícios",
  },
  {
    nome = "Luvas do Operário",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    periciaDistribuir = 4,
    periciaOpcoes = "Ofícios",
  },
  {
    nome = "Mochila do Peregrino",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    espacos = 2,
  },
  {
    nome = "Mochila do Peregrino",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    espacos = 4,
  },
  {
    nome = "Óculos do Espião",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    visaoEscuro = 12,
  },
  {
    nome = "Óculos do Espião",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    visaoEscuro = 14,
  },
  {
    nome = "Panela do Gastroquimista",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    periciaBonus = 2,
    periciaNome = "Gastronomia",
  },
  {
    nome = "Panela do Gastroquimista",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    periciaBonus = 4,
    periciaNome = "Gastronomia",
  },
  {
    nome = "Vara de Pescar",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Comum",
    slot = "acessorio",
    preco = { lunaris = 25 },
    durabilidade = 2,
    periciaBonus = 2,
    periciaNome = "Sobrevivência",
  },
  {
    nome = "Vara de Pescar",
    categoria = "Acessórios e Ferramentas",
    qualidade = "Ótima",
    slot = "acessorio",
    preco = { lunaris = 34 },
    durabilidade = 3,
    periciaBonus = 4,
    periciaNome = "Sobrevivência",
  },
  {
    nome = "Cantil de água",
    categoria = "Consumíveis",
    qualidade = "Comum",
    slot = "consumivel",
    preco = { florins = 2 },
    efeito = "Cantil que carrega água suficiente para saciar a sede de um mortal adulto por 1 dia.",
    subtipo = "Alimentação",
  },
  {
    nome = "Copo de cerveja ou vinho",
    categoria = "Consumíveis",
    qualidade = "Comum",
    slot = "consumivel",
    preco = { florins = 2 },
    efeito = "Corpo de cerveja ou hidromel, que deixam um mortal adulto alegre, e sacia sua sede temporariamente.",
    subtipo = "Alimentação",
  },
  {
    nome = "Ração de viagem",
    categoria = "Consumíveis",
    qualidade = "Comum",
    slot = "consumivel",
    preco = { florins = 4 },
    efeito = "Uma porção de ração de viagem que alimenta um mortal adulto, e que demora muito mais para estragar.",
    subtipo = "Alimentação",
  },
  {
    nome = "Refeição comum",
    categoria = "Consumíveis",
    qualidade = "Comum",
    slot = "consumivel",
    preco = { florins = 3 },
    efeito = "Uma refeição simples, preparada com ingredientes comuns, que alimenta um mortal adulto em uma refeição.",
    subtipo = "Alimentação",
  },
  {
    nome = "Sanduíche",
    categoria = "Consumíveis",
    qualidade = "Comum",
    slot = "consumivel",
    preco = { florins = 2 },
    efeito = "Um lanche que alimenta um mortal adulto, mas não sacia totalmente sua fome nem sua energia.",
    subtipo = "Alimentação",
  },
  {
    nome = "Poção de Cura",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido restaura 2d6+(Constituição+Rank) pontos de vida do usuário; Não reduz nível de ferimentos.",
    subtipo = "Remédio",
    curaDado = "2d6",
    curaFormula = "Constituição+Rank",
    curaTipo = "vida",
  },
  {
    nome = "Poção de Cura",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido restaura 3d6+(Constituição+Rank+1) pontos de vida do usuário; Não reduz nível de ferimentos",
    subtipo = "Remédio",
    curaDado = "3d6",
    curaFormula = "Constituição+Rank+1",
    curaTipo = "vida",
  },
  {
    nome = "Poção de Cura",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido restaura 4d6+(Contituição+Rank+2) pontos de vida do usuário; Não reduz nível de ferimentos",
    subtipo = "Remédio",
    curaDado = "4d6",
    curaFormula = "Contituição+Rank+2",
    curaTipo = "vida",
  },
  {
    nome = "Poção de Aura",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido restaura 2d6+(Constituição+Rank) pontos de aura do usuário.",
    subtipo = "Remédio",
    curaDado = "2d6",
    curaFormula = "Constituição+Rank",
    curaTipo = "aura",
  },
  {
    nome = "Poção de Aura",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido restaura 3d6+(Constituição+Rank+1) pontos de aura do usuário.",
    subtipo = "Remédio",
    curaDado = "3d6",
    curaFormula = "Constituição+Rank+1",
    curaTipo = "aura",
  },
  {
    nome = "Poção de Aura",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido restaura 4d6+(Contituição+Rank+2) pontos de aura do usuário.",
    subtipo = "Remédio",
    curaDado = "4d6",
    curaFormula = "Contituição+Rank+2",
    curaTipo = "aura",
  },
  {
    nome = "Poção de Mana",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido restaura 2d6+(Constituição+Rank) pontos de mana do usuário.",
    subtipo = "Remédio",
    curaDado = "2d6",
    curaFormula = "Constituição+Rank",
    curaTipo = "mana",
  },
  {
    nome = "Poção de Mana",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido restaura 3d6+(Constituição+Rank+1) pontos de mana do usuário.",
    subtipo = "Remédio",
    curaDado = "3d6",
    curaFormula = "Constituição+Rank+1",
    curaTipo = "mana",
  },
  {
    nome = "Poção de Mana",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido restaura 4d6+(Contituição+Rank+2) pontos de mana do usuário.",
    subtipo = "Remédio",
    curaDado = "4d6",
    curaFormula = "Contituição+Rank+2",
    curaTipo = "mana",
  },
  {
    nome = "Ungento medicinal",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Elimina um nível de ferimento ao ser passado sobre a área machucada; Não resolve amputações.",
    subtipo = "Remédio",
  },
  {
    nome = "Ungento medicinal",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Elimina dois níveis de ferimento ao ser passado sobre a área machucada; Não resolve amputações.",
    subtipo = "Remédio",
  },
  {
    nome = "Ungento medicinal",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Elimina três níveis de ferimento ao ser passado sobre a área machucada; Não resolve amputações.",
    subtipo = "Remédio",
  },
  {
    nome = "Antídoto",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido elimina o efeito [Envenenado] oriundo de origem comum, habilidade rank D ou poção de veneno amadora, adiciona por 3 turnos +2 em testes para resistir a venenos medianos ou rank C",
    subtipo = "Remédio",
  },
  {
    nome = "Antídoto",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido elimina o efeito [Envenenado] oriundo de origem comum, habilidade rank C ou poção de veneno mediana, adiciona por 3 turnos +2 em testes para resistir a venenos superiores ou rank B",
    subtipo = "Remédio",
  },
  {
    nome = "Antídoto",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido elimina o efeito [Envenenado] oriundo de origem comum, habilidade rank B ou poção de veneno superior, adiciona por 3 turnos +2 em testes para resistir a venenos perfeitos ou rank A",
    subtipo = "Remédio",
  },
  {
    nome = "Poção de Sono",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido ou inalado pelo alvo, este precisa rolar um teste de 1d20+Constituição com meta 14 para não ganhar o efeito [Adormecido] por 2 turnos ou 30 minutos fora de combate",
    subtipo = "Veneno",
  },
  {
    nome = "Poção de Sono",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido ou inalado pelo alvo, este precisa rolar um teste de 1d20+Constituição com meta 16 para não ganhar o efeito [Adormecido] por 3 turnos ou 1 hora fora de combate",
    subtipo = "Veneno",
  },
  {
    nome = "Poção de Sono",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido ou inalado pelo alvo, este precisa rolar um teste de 1d20+Constituição com meta 18 para não ganhar o efeito [Adormecido] por 4 turnos ou 2 horas fora de combate",
    subtipo = "Veneno",
  },
  {
    nome = "Raiva de Tofana",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido ou inalado pelo alvo, este precisa rolar um teste de 1d20+Constituição com meta 14 para não receber o efeito [Envenenado] recebendo 2d6 de dano por 2 turnos.",
    subtipo = "Veneno",
  },
  {
    nome = "Raiva de Tofana",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido ou inalado pelo alvo, este precisa rolar um teste de 1d20+Constituição com meta 16 para não receber o efeito [Envenenado] recebendo 3d6 de dano por 3 turnos.",
    subtipo = "Veneno",
  },
  {
    nome = "Raiva de Tofana",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido ou inalado pelo alvo, este precisa rolar um teste de 1d20+Constituição com meta 18 para não receber o efeito [Envenenado] recebendo 4d6 de dano por 4 turnos.",
    subtipo = "Veneno",
  },
  {
    nome = "Elixir da Ira",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido você entra automaticamente na condição [Enfurecido] por 2 turnos.",
    subtipo = "Tônico",
  },
  {
    nome = "Elixir da Ira",
    categoria = "Consumíveis",
    qualidade = "Mediano",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido você entra automaticamente na condição [Enfurecido] por 3 turnos.",
    subtipo = "Tônico",
  },
  {
    nome = "Elixir da Ira",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido você entra automaticamente na condição [Enfurecido] por 4 turnos",
    subtipo = "Tônico",
  },
  {
    nome = "Poção de Fortitude",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido aumenta as Defesas Físicas em +1 por 2 turnos.",
    subtipo = "Tônico",
  },
  {
    nome = "Poção de Fortitude",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido aumenta as Defesas Físicas em +2 por 3 turnos.",
    subtipo = "Tônico",
  },
  {
    nome = "Poção de Fortitude",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido aumenta as Defesas Físicas em +3 por 4 turnos.",
    subtipo = "Tônico",
  },
  {
    nome = "Poção Psíquica",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido aumenta as Defesas Telepática em +1 por 2 turnos.",
    subtipo = "Tônico",
  },
  {
    nome = "Poção Psíquica",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido aumenta as Defesas Telepática em +2 por 3 turnos.",
    subtipo = "Tônico",
  },
  {
    nome = "Poção Psíquica",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido aumenta as Defesas Telepática em +3 por 4 turnos.",
    subtipo = "Tônico",
  },
  {
    nome = "Poção Empática",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido aumenta as Defesas Empática em +1 por 2 turnos.",
    subtipo = "Tônico",
  },
  {
    nome = "Poção Empática",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido aumenta as Defesas Empática em +2 por 3 turnos.",
    subtipo = "Tônico",
  },
  {
    nome = "Poção Empática",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido aumenta as Defesas Empática em +3 por 4 turnos.",
    subtipo = "Tônico",
  },
  {
    nome = "Tônico Energético",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido mantém o usuário acordado por 24 horas enquanto se mantiver vivo; Após o período o sono será compensado.",
    subtipo = "Tônico",
  },
  {
    nome = "Tônico Energético",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido mantém o usuário acordado por 48 horas enquanto se mantiver vivo; Após o período o sono será compensado.",
    subtipo = "Tônico",
  },
  {
    nome = "Tônico Energético",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido mantém o usuário acordado por 72 horas enquanto se mantiver vivo; Após o período o sono será compensado.",
    subtipo = "Tônico",
  },
  {
    nome = "Tônico Boêmio",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao ser consumido elimina parcialmente os efeitos de [Embriagado] e [Entorpecido] do alvo; O próximo teste para resistir a estes efeitos será rolado com +1.",
    subtipo = "Tônico",
  },
  {
    nome = "Tônico Boêmio",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser consumido elimina totalmente os efeitos de [Embriagado] e [Entorpecido] do alvo; O próximo teste para resistir a estes efeitos será rolado com +2",
    subtipo = "Tônico",
  },
  {
    nome = "Tônico Boêmio",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser consumido garante resistênica contra futuros testes de [Embriagado] e [Entorpecido] do alvo; O próximo teste para resistir a estes efeitos será rolado com +3",
    subtipo = "Tônico",
  },
  {
    nome = "Bomba Flamejante",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Fogo] que aplica 3d6 de dano em um raio de 2 metros; Cria fogo que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Flamejante",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Fogo] que aplica 4d6 de dano em um raio de 4 metros; Cria fogo que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Flamejante",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Fogo] que aplica 5d6 de dano em um raio de 6 metros; Cria fogo que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Elétrica",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Eletricidade] que aplica 3d6 de dano em um raio de 2 metros; Cria uma onda de choque que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Elétrica",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Eletricidade] que aplica 4d6 de dano em um raio de 4 metros; Cria uma onda de choque que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Elétrica",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Eletricidade] que aplica 5d6 de dano em um raio de 6 metros; Cria uma onda de choque que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Aquática",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Água] que aplica 3d6 de dano em um raio de 2 metros; Cria uma onda de água que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Aquática",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Água] que aplica 4d6 de dano em um raio de 4 metros; Cria uma onda de água que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Aquática",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Água] que aplica 5d6 de dano em um raio de 6 metros; Cria uma onda de água que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Terrana",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Terra] que aplica 3d6 de dano em um raio de 2 metros; Cria uma onda de terra que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Terrana",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Terra] que aplica 4d6 de dano em um raio de 4 metros; Cria uma onda de terra que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Terrana",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Terra] que aplica 5d6 de dano em um raio de 6 metros; Cria uma onda de terra que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Vegetal",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Planta] que aplica 3d6 de dano em um raio de 2 metros; Cria uma onda de vinhas e raízes que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Vegetal",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Planta] que aplica 4d6 de dano em um raio de 4 metros; Cria uma onda de vinhas e raízes que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Vegetal",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Planta] que aplica 5d6 de dano em um raio de 6 metros; Cria uma onda de vinhas e raízes que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Solar",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Dia] que aplica 3d6 de dano em um raio de 2 metros; Cria um forte flash que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Solar",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Dia] que aplica 4d6 de dano em um raio de 4 metros; Cria um forte flash que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Solar",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Dia] que aplica 5d6 de dano em um raio de 6 metros; Cria um forte flash que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Sombria",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Noite] que aplica 3d6 de dano em um raio de 2 metros; Cria uma nuvem de escuridão que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Sombria",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Noite] que aplica 4d6 de dano em um raio de 4 metros; Cria uma nuvem de escuridão que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Sombria",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Noite] que aplica 5d6 de dano em um raio de 6 metros; Cria uma nuvem de escuridão que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Gelada",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Gelo] que aplica 3d6 de dano em um raio de 2 metros; Cria uma onda de neve e gelo que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Gelada",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Gelo] que aplica 4d6 de dano em um raio de 4 metros; Cria uma onda de neve e gelo que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Gelada",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Gelo] que aplica 5d6 de dano em um raio de 6 metros; Cria uma onda de neve e gelo que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Sagrada",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Sagrado] que aplica 3d6 de dano em um raio de 2 metros; Cria uma área sagrada que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Sagrada",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Sagrado] que aplica 4d6 de dano em um raio de 4 metros; Cria uma área sagrada que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Sagrada",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Sagrado] que aplica 5d6 de dano em um raio de 6 metros; Cria uma área sagrada que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Eólica",
    categoria = "Consumíveis",
    qualidade = "Amadora",
    slot = "consumivel",
    preco = { lunaris = 15 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Vento] que aplica 3d6 de dano em um raio de 2 metros; Cria um pequeno tufão que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Eólica",
    categoria = "Consumíveis",
    qualidade = "Mediana",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Vento] que aplica 4d6 de dano em um raio de 4 metros; Cria um pequeno tufão que irá interagir com o terreno",
    subtipo = "Bomba",
  },
  {
    nome = "Bomba Eólica",
    categoria = "Consumíveis",
    qualidade = "Superior",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao cair sobre um alvo aplica uma explosão de [Vento] que aplica 5d6 de dano em um raio de 6 metros; Cria um pequeno tufão que irá interagir com o terreno Granadas: Granadas são itens consumíveis com objetivo destrutivo, sua diferença para as bombas é que as bombas elementais são feitas por alquimistas, enquanto granadas são criadas por mecânicos.",
    subtipo = "Bomba",
  },
  {
    nome = "Granada",
    categoria = "Consumíveis",
    qualidade = "Comum",
    slot = "consumivel",
    preco = { lunaris = 5 },
    areaRaio = 2,
    danoArea = "5d6",
    areaElemento = "Neutro",
    efeito = "Consumível; Qualidade Comum; [1x Aço e 1x Pólvora]; Criação meta 16; Aplica 5d6 de dano [Neutro] em um raio de 2 metros.",
  },
  {
    nome = "Granada",
    categoria = "Consumíveis",
    qualidade = "Ótima",
    slot = "consumivel",
    preco = { lunaris = 10 },
    areaRaio = 3,
    danoArea = "6d6",
    areaElemento = "Neutro",
    efeito = "Consumível; Qualidade Ótima; [1x Aço e 1x Pólvora]; Criação meta 20; Aplica 6d6 de dano [Neutro] em um raio de 3 metros.",
  },
  {
    nome = "Granada",
    categoria = "Consumíveis",
    qualidade = "Excepcional",
    slot = "consumivel",
    preco = { lunaris = 20 },
    areaRaio = 4,
    danoArea = "8d6",
    areaElemento = "Neutro",
    efeito = "Consumível; Qualidade Excepcional; [1x Aço e 2x Pólvora]; Criação meta 24; Aplica 8d6 de dano [Neutro] em um raio de 4 metros; Pode ser imbuida com elementos ou encantamentos temporários",
  },
  {
    nome = "Granada",
    categoria = "Consumíveis",
    qualidade = "Artíficie",
    slot = "consumivel",
    preco = { aureus = 1 },
    areaRaio = 6,
    danoArea = "11d6",
    areaElemento = "Neutro",
    efeito = "Consumível; Qualidade Lendária; [2x Aço e 2x Pólvora]; Criação meta 30; Aplica 11d6 de dano [Neutro] em um raio de 6 metros; Pode ser imbuida com elementos ou encantamentos temporários Pergaminhos de habilidades Pergaminhos de habilidades são objetos feitos por personagens da subclasse Estudioso (Devoto), que consistem em uma série de inscrições arcanas em um pedaço de papel preparado que captura a aura de um Ser/Criatura durante um uso de sua habilidade. Cada pergaminho funciona como um consumivel , onde seu usuário o utiliza para ter a capacidade de usar uma vez a habilidade ali presente. É possível armazenar em um pergaminho habilidades de qualquer tipo ou rank, dependendo única e exclusivamente da capacidade do Estudioso em preparar o objeto e encontrar um Ser ou Criatura com uma skill do respectivo nível. Restrição: somente é permitido utilizar os pergaminhos de habilidade por personagens que saibam ler (3 de Inteligência + perícia \"Acadêmicos\"). Preço dos Pergaminhos: Rank D: 25 Lunaris Rank C: 1 Aureu Rank B: 1 Aureus e 25 Lunaris Rank A: 2 Aureus Estoque de pergaminhos:",
  },
  {
    nome = "Armadura de areia",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Protege o corpo do alvo com uma segunda pele de [Areia] que absorve 2d6+[Rank] pontos de toda fonte de dano por 2 turnos, alcance de 4 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Armadura de areia",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Protege o corpo do alvo com uma segunda pele de [Areia] que absorve 3d6+[Rank] pontos de toda fonte de dano por 2 turnos, alcance de 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Dissipar elemento",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "O pergaminho absorve um elemento que esteja em uma [Área] de 3 metros de raio, pode ser usado contra habilidades de até Rank D.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Dissipar elemento",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "O pergaminho absorve um elemento que esteja em uma [Área] de 4 metros de raio, pode ser usado contra habilidades de até Rank C.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Dissipar magia",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "O pergaminho absorve completamente toda magia em uma [Área] de 3 metros de raio, pode ser usado contra feitiços de até Rank D.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Dissipar magia",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "O pergaminho absorve completamente toda magia em uma [Área] de 4 metros de raio, pode ser usado contra feitiços de até Rank C.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Escudo mágico",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "maos",
    preco = { lunaris = 25 },
    efeito = "Gera um escudo esférico de [Magia] que protege todos em uma [Area] de 3 metros de raio por até 2 turnos, aqueles dentro podem sair mas os de fora não conseguem entrar.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Escudo mágico",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "maos",
    preco = { aureus = 1 },
    efeito = "Gera um escudo esférico de [Magia] que protege todos em uma [Area] de 4 metros de raio por até 2 turnos, aqueles dentro podem sair mas os de fora não conseguem entrar.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Esfera de chamas",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Arremessa uma esfera pequena de [Fogo] em um local, que causa uma explosão de 2d6 em uma [Área] de 3 metros de raio. Acerto: Inteligência + Bônus proficiência",
    subtipo = "Pergaminho",
  },
  {
    nome = "Esfera de chamas",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Arremessa uma esfera pequena de [Fogo] em um local, que causa uma explosão de 3d6 em uma [Área] de 4 metros de raio. Acerto: Inteligência + Bônus proficiência",
    subtipo = "Pergaminho",
  },
  {
    nome = "Expandir recipientes",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser aplicado sobre um baú, barril, caixa ou mochila amplia em 3 pontos sua capacidade por 3 dias.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Expandir recipientes",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser aplicado sobre um baú, barril, caixa ou mochila amplia em 4 pontos sua capacidade por 5 dias.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Falar com animais",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Aplica sobre o alvo a capacidade de falar com animais por até 5 minutos, ou realizar duas perguntas válidas , alcance de até 3 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Falar com animais",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Aplica sobre o alvo a capacidade de falar com animais por até 5 minutos, ou realizar três perguntas válidas , alcance de até 4 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Falar com cadáveres",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Quando usado em um cadáver, ele acordará por até 5 minutos e poderá responder um máximo de duas perguntas válidas nos idiomas que sabia falar, alcance de até 3 metros",
    subtipo = "Pergaminho",
  },
  {
    nome = "Falar com cadáveres",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Quando usado em um cadáver, ele acordará por até 5 minutos e poderá responder um máximo de três perguntas válidas nos idiomas que sabia falar, alcance de até 4 metros",
    subtipo = "Pergaminho",
  },
  {
    nome = "Falar com plantas",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Aplica sobre o alvo a capacidade de falar com plantas por até 5 minutos, ou realizar duas perguntas válidas, alcance de até 3 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Falar com plantas",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Aplica sobre o alvo a capacidade de falar com plantas por até 5 minutos, ou realizar duas perguntas válidas, alcance de até 3 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Faxina arcana",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser aplicado sobre uma [Area] de até 6 metros de raio e 12 metros de altura, realiza uma limpeza completa, inclusive pequenos reparos comuns em móveis, portas e janelas.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Faxina arcana",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser aplicado sobre uma [Area] de até 8 metros de raio e 18 metros de altura, realiza uma limpeza completa, inclusive reparos médios comuns em móveis, portas e janelas.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir água",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Imbui uma arma com o elemento [Água] por 2 turnos, alcance de até 4 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir água",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Imbui uma arma com o elemento [Água] por 2 turnos; Aplica 1d6 de dano adicional do mesmo elemento; Alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir eletricidade",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Imbui uma arma com o elemento [Eletricidade] por 2 turnos, alcance de até 4 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir eletricidade",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Imbui uma arma com o elemento [Eletricidade] por 2 turnos; Aplica 1d6 de dano adicional do mesmo elemento; Alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir fogo",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Imbui uma arma com o elemento [Fogo] por 2 turnos, alcance de até 4 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir fogo",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Imbui uma arma com o elemento [Fogo] por 2 turnos; Aplica 1d6 de dano adicional do mesmo elemento; Alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir gelo",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Imbui uma arma com o elemento [Gelo] por 2 turnos, alcance de até 4 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir gelo",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Imbui uma arma com o elemento [Gelo] por 2 turnos; Aplica 1d6 de dano adicional do mesmo elemento; Alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir luz",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Imbui uma arma com o elemento [Dia] por 2 turnos; alcance de até 4 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir luz",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Imbui uma arma com o elemento [Dia] por 2 turnos; Aplica 1d6 de dano adicional do mesmo elemento; Alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir magia",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Imbui uma arma com [Magia] por 2 turnos; alcance de até 4 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir magia",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Imbui uma arma com [Magia] por 2 turnos; Aplica 1d6 de dano adicional do mesmo elemento; Alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir sombra",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Imbui uma arma com [Noite] por 2 turnos; alcance de até 4 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir sombra",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Imbui uma arma com [Noite] por 2 turnos; Aplica 1d6 de dano adicional do mesmo elemento; Alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir terra",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Imbui uma arma com [Terra] por 2 turnos; alcance de até 4 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir terra",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Imbui uma arma com [Terra] por 2 turnos; Aplica 1d6 de dano adicional do mesmo elemento; Alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir vento",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Imbui uma arma com [Vento] por 2 turnos; alcance de até 4 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Imbuir vento",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Imbui uma arma com [Vento] por 2 turnos; Aplica 1d6 de dano adicional do mesmo elemento; Alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Intérprete",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Aplica sobre um alvo a capacidade de compreender, por 3 minutos, qualquer idioma enquanto estiver em uma conversa com alguém.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Intérprete",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Aplica sobre um alvo a capacidade de compreender, por 30 minutos, qualquer idioma enquanto estiver em uma conversa com alguém.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Invocar mensageiro",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Invoca uma pequena ave que carrega um pergaminho onde uma mensagem de até 200 letras pode ser escrita; O mensageiro voa por até 3 dias.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Invocar mensageiro",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Invoca uma pequena ave que carrega um pergaminho onde uma mensagem de até 500 letras pode ser escrita; O mensageiro voa por até 7 dias.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Manto de sombras",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Uma aura de sombras encobre um alvo lhe garantindo +2 em testes de Furtividade contra a Sabedoria de um alvo para ficar [Invisível] por 2 turnos.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Manto de sombras",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Uma aura de sombras encobre um alvo lhe garantindo +3 em testes de Furtividade contra a Sabedoria de um alvo para ficar [Invisível] por 2 turnos.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Metamorfose animal \"Pelicano\"",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "O usuário se transforma por 3 turnos (ou 3 horas fora de combate) em um Pelicano; Se torna capaz de voar e falar com tais animais.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Metamorfose animal \"Pelicano\"",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "O usuário se transforma por 4 turnos (ou 6 horas fora de combate) em um Pelicano; Se torna capaz de voar e falar com tais animais além de cegonhas ou gaivotas.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Metamorfose animal \"Bode\"",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "O usuário se transforma por 3 turnos (ou 3 horas fora de combate) em um Bode; Se torna capaz de falar com tais animais.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Metamorfose animal \"Bode\"",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "O usuário se transforma por 4 turnos (ou 6 horas fora de combate) em um Bode; Se torna capaz de falar com tais animais além de ovelhas, cabras, carneiros e bisões.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Metamorfose animal \"Baiacu\"",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "O usuário se transforma por 3 turnos (ou 3 horas fora de combate) em um Baiacu; Se torna capaz de respirar embaixo da água e falar com tais animais.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Metamorfose animal \"Baiacu\"",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "O usuário se transforma por 3 turnos (ou 6 horas fora de combate) em um Baiacu; Se torna capaz de respirar embaixo da água e falar com tais animais além peixes de pequeno e médio porte.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Parede de terra",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ergue uma parede de [Terra] com 30 pontos de vida e 4 metros de altura que se mantém no local por 2 turnos, a parede possuí 1 metros de largura.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Parede de terra",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ergue uma parede de [Terra] com 40 pontos de vida e 5 metros de altura que se mantém no local por 3 turnos, a parede possuí 2 metros de largura.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Passo iluminado",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "O alvo se desfaz em minúsculos fótons de [Luz], e então se teleporta para outro lugar que o usuário possa ver a no máximo 08 metros de distância.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Passo iluminado",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "O alvo se desfaz em minúsculos fótons de [Luz], e então se teleporta para outro lugar que o usuário possa ver a no máximo 10 metros de distância.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Prisão de bolha",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Uma prisão de [Água] que mantém um alvo preso/submerso por 2 turnos. Somente quebravel por fora [24 de HP] de uma vez, alcance de 6 metros. Acerto: Inteligência + Bônus proficiência",
    subtipo = "Pergaminho",
  },
  {
    nome = "Prisão de bolha",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Uma prisão de [Água] que mantém um alvo preso/submerso por 2 turnos. Somente quebravel por fora [36 de HP] de uma vez, alcance de 8 metros. Acerto: Inteligência + Bônus proficiência",
    subtipo = "Pergaminho",
  },
  {
    nome = "Raio trovejante",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Lança um raio [Elétrico] que aplica 2d6 de dano em um alvo que esteja em uma distância de até 6 metros. Acerto: Inteligência + Bônus proficiência .",
    subtipo = "Pergaminho",
  },
  {
    nome = "Raio trovejante",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Lança um raio [Elétrico] que aplica 3d6 de dano em um alvo que esteja em uma distância de até 8 metros. Acerto: Inteligência + Bônus proficiência .",
    subtipo = "Pergaminho",
  },
  {
    nome = "Revelar oculto",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Garante +2 em testes de Percepção e Investigação para encontrar inimigos, entradas ou objetos ocultos em até 6 metros de distância do usuário.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Revelar oculto",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Garante +3 em testes de Percepção e Investigação para encontrar inimigos, entradas ou objetos ocultos em até 8 metros de distância do usuário.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Remover envenenamento",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser utilizado remove no alvo efeitos de envenenamento de até rank D , alcance de 6 até metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Remover envenenamento",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser utilizado remove no alvo efeitos de envenenamento de até rank C , alcance de 6 até metros; Aplicável em até duas pessoas.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Restaurar equipamento",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser aplicado sobre qualquer equipamento, remove quaisquer tipos de efeitos negativos de até rank D",
    subtipo = "Pergaminho",
  },
  {
    nome = "Restaurar equipamento",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser aplicado sobre qualquer equipamento, remove quaisquer tipos de efeitos negativos de até rank C",
    subtipo = "Pergaminho",
  },
  {
    nome = "Tratar doença",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser utilizado cura doenças não-crônicas de grau leve no alvo, ou causadas por habilidades/magias de até Rank D , alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Tratar doença",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser utilizado cura doenças não-crônicas de grau leve no alvo, ou causadas por habilidades/magias de até Rank C , alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Tratar ferimentos",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Ao ser utilizado em um alvo com status Ferido elimina automaticamente um nível de ferimento, alcance de até 6 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Tratar ferimentos",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Ao ser utilizado em um alvo com status Ferido elimina automaticamente dois níveis de ferimento, alcance de até 8 metros.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Toque do espião",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Dá a capacidade de se transformar em alguém tocando no alvo; Apenas copia a aparência e a voz por 2 horas ou turnos em combate.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Toque do espião",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Dá a capacidade de se transformar em alguém tocando no alvo; Apenas copia a aparência e a voz por 6 horas ou 3 turnos em combate.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Vôo curto",
    categoria = "Consumíveis",
    qualidade = "Rank D",
    slot = "consumivel",
    preco = { lunaris = 25 },
    efeito = "Realiza um vôo por até 2 turnos e máxima de 12 metros, respeitando o limite de seu deslocamento +2 metros para cada ação de movimentação.",
    subtipo = "Pergaminho",
  },
  {
    nome = "Vôo curto",
    categoria = "Consumíveis",
    qualidade = "Rank C",
    slot = "consumivel",
    preco = { aureus = 1 },
    efeito = "Realiza um vôo por até 2 turnos e máxima de 14 metros, respeitando o limite de seu deslocamento +3 metros para cada ação de movimentação.",
    subtipo = "Pergaminho",
  },
}

local function normalizar(s)
  s = tostring(s or ""):lower()
  local de = {["á"]="a",["à"]="a",["ã"]="a",["â"]="a",["é"]="e",["ê"]="e",["í"]="i",
              ["ó"]="o",["ô"]="o",["õ"]="o",["ú"]="u",["ü"]="u",["ç"]="c"}
  for k, v in pairs(de) do s = s:gsub(k, v) end
  return (s:gsub("[^a-z0-9]", ""))
end

function CatalogoItens.buscar(nome, qualidade)
  for _, it in ipairs(CatalogoItens.itens) do
    if normalizar(it.nome) == normalizar(nome)
       and (qualidade == nil or normalizar(it.qualidade) == normalizar(qualidade)) then
      return it
    end
  end
  return nil
end

function CatalogoItens.categorias()
  local vistas, ordem = {}, {}
  for _, it in ipairs(CatalogoItens.itens) do
    if not vistas[it.categoria] then
      vistas[it.categoria] = true
      table.insert(ordem, it.categoria)
    end
  end
  return ordem
end

function CatalogoItens.porCategoria(cat)
  local r = {}
  for _, it in ipairs(CatalogoItens.itens) do
    if it.categoria == cat then table.insert(r, it) end
  end
  return r
end

-- Preco em Drams, para somar ou comparar.
function CatalogoItens.precoEmDrams(preco)
  local total = 0
  for moeda, qtd in pairs(preco or {}) do
    total = total + (qtd * (CatalogoItens.valorEmDrams[moeda] or 0))
  end
  return total
end

-- Texto curto do preco, na moeda em que o livro escreve.
function CatalogoItens.precoTexto(preco)
  local partes = {}
  for _, moeda in ipairs(CatalogoItens.moedas) do
    local qtd = (preco or {})[moeda]
    if qtd ~= nil and qtd > 0 then
      table.insert(partes, qtd .. " " .. CatalogoItens.nomeMoeda[moeda])
    end
  end
  if #partes == 0 then return "—" end
  return table.concat(partes, " e ")
end

-- Resumo dos efeitos, para listar no card e na linha do item.
function CatalogoItens.resumo(it)
  if it == nil then return "" end
  local p = {}
  if it.dado ~= nil then table.insert(p, it.dado) end
  if it.danoExtra ~= nil then table.insert(p, "+" .. it.danoExtra .. " de dano") end
  if it.alcance ~= nil then table.insert(p, it.alcance .. "m") end
  if it.alcanceExtra ~= nil then table.insert(p, "+" .. it.alcanceExtra .. "m ao alcance da arma") end
  if it.defesaAparar ~= nil then table.insert(p, "+" .. it.defesaAparar .. " Aparar") end
  if it.defesaEscolha ~= nil then
    if it.defesaLista ~= nil then
      table.insert(p, "+" .. it.defesaEscolha .. " entre " .. it.defesaLista)
    else
      table.insert(p, "+" .. it.defesaEscolha .. " em 2 defesas à escolha")
    end
  end
  if it.absorcao ~= nil then table.insert(p, it.absorcao .. "% absorção") end
  if it.deslocamento ~= nil then table.insert(p, it.deslocamento .. "m deslocamento") end
  if it.periciaBonus ~= nil then
    if it.periciaNome ~= nil then
      table.insert(p, "+" .. it.periciaBonus .. " em " .. it.periciaNome)
    else
      table.insert(p, "+" .. it.periciaBonus .. " numa perícia")
    end
  end
  if it.municoes ~= nil then table.insert(p, it.municoes .. " munições") end
  if it.espacos ~= nil then table.insert(p, "+" .. it.espacos .. " espaços de mochila") end
  if it.capacidade ~= nil then
    table.insert(p, "carrega " .. it.capacidade .. " " .. tostring(it.capacidadeTipo or ""))
  end
  if it.visaoEscuro ~= nil then table.insert(p, "+" .. it.visaoEscuro .. "m de visão no escuro") end
  if it.danoArea ~= nil then
    table.insert(p, it.danoArea .. " [" .. tostring(it.areaElemento or "") .. "] em " ..
      tostring(it.areaRaio or "?") .. "m de raio")
  end
  if it.periciaOpcoes ~= nil then
    table.insert(p, "à escolha entre: " .. it.periciaOpcoes)
  end
  -- defesaLista ja aparece junto do valor, logo acima
  if it.durabilidade ~= nil then table.insert(p, it.durabilidade .. " de durabilidade") end
  if it.reqAtributo ~= nil then table.insert(p, "requer " .. it.reqValor .. " de " .. it.reqAtributo) end
  if it.curaDado ~= nil then
    table.insert(p, "restaura " .. it.curaDado .. "+(" .. tostring(it.curaFormula) ..
      ") de " .. tostring(it.curaTipo))
  end
  if it.efeito ~= nil and #p == 0 then table.insert(p, it.efeito) end
  return table.concat(p, "  ·  ")
end

return CatalogoItens
